### ISSUE TITLE
When 'smoothLivePreview' is true, change the svg placeholder for the actual iframe when the user clicks on the svg

### ISSUE THREAD

**Issue by RamiroPastor** [showdownjs/youtube-extension#16]
I can live without this if it's too hard to implement.

But i think it could be much better like this, preserving the "smoothness" while convincing the user that the video will be correctly embedded.

**Comment by tivie** [comment]
Unfortunately that cannot be done through showdown.

The user click event happens after showdown has already completed the parsing so it no longer has any kind of control over the content.

So, you need to catch the user click event and wire the substitution outside showdown.

**Comment by RamiroPastor** [comment]
Ok, thanks for the attention
