### ISSUE TITLE
Youtube video size is to small

### ISSUE THREAD

**Issue by CyborTronik** [showdownjs/youtube-extension#4]
Hi, Youtube videos are integrated well into markdown but is too small.
So is there a way to make it resizeble/flexible sizes for different screens. 
So on big screen should be bigger on small one to fit the width.

**Comment by CyborTronik** [comment]
You can see example there how to implement that: http://foundation.zurb.com/docs/components/flex_video.html

**Comment by tivie** [comment]
I'm on this issue... I will release an updated version as soon as possible

**Comment by tivie** [comment]
(in the meanwhile, you can fix window size with css and/or javascript)

**Comment by CyborTronik** [comment]
It make sense to make generated code to be configurable and then let users by themselve to solve the size. But will be ideal to have by default such behavior.

**Comment by tivie** [comment]
The plan is to use the image size syntax.

**Comment by tivie** [comment]
check version 1.0.0

You can use image size syntax to set the video size:

```
![foo](https://www.youtube.com/watch?v=Do1lm9IevYE =200x500)
```
